import PayrollProvider from "@/contexts/PayrollContext";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import DashboardProvider from "@/contexts/DashboardContext";
import CustomLayout from "@/components/layout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <DashboardProvider>
          <PayrollProvider>
            <CustomLayout>
              {children}
            </CustomLayout>
          </PayrollProvider>
        </DashboardProvider>
      </body>
    </html>
  );
}
